### ISSUE TITLE
Download for Szilard Pafka slides not working

### ISSUE THREAD

**Issue by revodavid** [eddelbuettel/rf2#5]
In the Program entry:

> Szilard Pafka: No-Bullshit Data Science (pdf) (video)

The PDF link points to http://past.rinfinance.com/agenda/2017/talk/SzilardPafka.pdf but that URL returns a 404.

**Comment by eddelbuettel** [comment]
I could swear I tried that at home.  Hold on.

**Comment by eddelbuettel** [comment]
Try now. It was a manual copying error -- I had SzilardPafka.html instead.

So big thanks for report.  And quicker here than first reporting to Mary :)

**Comment by revodavid** [comment]
Yep, works now, thanks.
